apiVersion: kaptain.org/1.15
kind: docker-build-dockerfile
metadata:
  description: "AWS EKS cluster management image"

spec:
  layers:
    - layer-github-flow-strict:[1.3,2.0)
  main:
    docker:
      platform: linux/amd64,linux/arm64
      dockerfile:
        subPathLinuxAmd64: src/docker
        subPathLinuxArm64: src/docker
    hooks:
      preTaggingTests: .github/bin/run-tests.bash
      preDockerPrepare: .github/bin/copy-scripts-to-docker-context.bash
  global:
    release:
      versioning:
        maxParts: '2'
